### ISSUE TITLE
Arc-cosine operation on LazyTensors

### ISSUE THREAD

**Issue by fwilliams** [getkeops/keops#104]
I would like to use KeOps with arc-cosine kernels but it appears there is no `arccos` operation. 

It would also be useful to have an equivalent to `torch.clamp` (to ensure the input to `arccos` is in `[0, 1]`).

Thanks!

**Comment by jeanfeydy** [comment]
Hi @fwilliams ,

Thanks a lot for #105 (adds support for arccos): it's great to see that you were able to add it to the core engine without too much trouble!

Clamp may be a bit harder to implement properly: in full generality, this is a 3-ary operator (tensor value + lower bound + upper bound) and I don't think that we've added support for them just yet. Until then, the best workaround is probably to use `K.concat(LazyTensor(0)).max().concat(LazyTensor(1)).min()` as a proxy for `K.clamp(0, 1)`.

Tomorrow morning, I will have a meeting with @joanglaunes and @bcharlier to decide what goes in the v1.4.2 release: acos will certainly be included. For clamp, we'll have to choose between adding full support for ternary ops, or emulate the expected behaviour of clamp using a binary op "`Clamp(K, [min, max])`". 
In any case, thanks again for your suggestion and PR: we probably won't meet in person anytime soon, but I'd be happy to have a chat with you when you'll have the time :-)

Best regards,
Jean

**Comment by joanglaunes** [comment]
Hello @fwilliams and @jeanfeydy ,
I think adding support for ternary operations is really not a big deal, and then we can add also an "if x then y else z" operation, which was also requested by others. Then for Clamp we can add the general ternary operation clamp(x, min,max), as well as a unary operation where min and max are fixed integers, which should be probably a bit faster.

Joan

**Comment by fwilliams** [comment]
Hi @jeanfeydy and @joanglaunes. Thank you both for your replies! And thanks for this well written library, it was very easy to figure out how things worked internally. 

Support for ternary operations would be fantastic, and if I get some spare cycles I might try and add my own implementation and send a PR. In the meantime, I've hacked a `Clamp11(x)` function into my fork which just clamps a value between -1 and 1 (which is all I need for now). 

I'll also send a PR with arcsin and arctan in addition to arccos (since it does make sense to have all of these). If I have time, I might even take a crack at adding ternary operator support.

**Comment by joanglaunes** [comment]
Hello @fwilliams ,
Thanks a lot doing all this stuff ! About Ternary operations, in fact I had started to write it in a separate branch two days ago, so please wait a little bit at this point. The thing is that I am about to merge another branch (named genchunk) which does modifications to UnaryOp and BinaryOp files. So I am writing TernaryOp based on the models in that branch.
Also if you have time, if you can modify your Clamp11<F> in order to do a more general ClampInt<F,MIN,MAX> it would be great. This would be still a Unary operation, MIN and MAX are then just extra fixed parameters, you can look at the similar Pow operation which has one extra integer parameter.

**Comment by joanglaunes** [comment]
Hi @fwilliams ,
You may have seen that we have now merged your branch into master. Also I have added the support for ternary operations, as well as the clamp operation. There is an example script in pykeops/sandbox. When calling `x.clamp(a,b)` in the Python interface,
- if `a` and `b` are integers, it redirects to the unary `ClampInt` operation of the C++ code (slightly faster),
- if `a` and `b` are floats, or if they are other LazyTensors, it redirects to the ternary `Clamp` operation. So `a` and `b` can be tensors or other formulas, provided `x`, `a` and `b` have compatible shapes with respect to broadcasting rules.

**Comment by kshitij12345** [comment]
First of all a great project!

I would like to start contributing if possible. I see that `asin` and `atan` are still pending and would like to give them a shot.
Will be referring to @fwilliams PR for `acos`.

Would that be okay?
@fwilliams  @joanglaunes

**Comment by jeanfeydy** [comment]
Hi @kshitij12345 ,

Thanks for your kind words - and of course, your PR would be more than welcome!
I am currently writing a contribution guide in the documentation - but for standard mathematical formulas, you should be good to go already with @fwilliams 's fine PR template.

Of course, if you find something strange or have any other question, **please let us know**. We've tried to explain the inner workings of the KeOps C++ engine [in the doc](https://www.kernel-operations.io/keops/formulas/math_operations.html), but some parts may now be a bit outdated or unclear. Feedback from users and other developers is key to making this toolbox useful :-)

Best regards,
Jean

**Comment by kshitij12345** [comment]
Thanks for the quick reply!

> Of course, if you find something strange or have any other question, please let us know. We've tried to explain the inner workings of the KeOps C++ engine in the doc, but some parts may now be a bit outdated or unclear. Feedback from users and other developers is key to making this toolbox useful :-)

Will surely let you know.

**Comment by adam-coogan** [comment]
Hi! I was wondering about the status of the ternary "if `x` then `y` else `z`" operator referred to further up in this thread. I would find this quite useful.

**Comment by joanglaunes** [comment]
I think that all enhancements discussed here have been included into KeOps now ; so I am closing the issue.
