### ISSUE TITLE
ValueError: Incompatible values for attribute ni

### ISSUE THREAD

**Issue by wzm2256** [getkeops/keops#106]
I also run into a batch dimension bug. Actually, I'm trying to implement a batch version of geoloss library (the ''online'' backend), but my code simply does not work due to a similar bug as in https://github.com/getkeops/keops/issues/103 even without back propagation. I provide a minimal example in the following.

```python
import torch
from pykeops.torch import LazyTensor

device = 'cpu'
x = torch.randn((8, 1000, 3), dtype=torch.float, device=device)
y = torch.randn((8, 1500, 3), dtype=torch.float, device=device)
u = torch.randn((8, 1, 1500), dtype=torch.float, device=device)
eps = torch.tensor(1., dtype=torch.float, device=device)

x_ = LazyTensor(x.reshape((8, 1000, 1, 3)))
y_ = LazyTensor(y.reshape((8, 1, 1500, 3)))
u_ = LazyTensor(u)
eps_ = LazyTensor(eps)

# Dis2 = ((x_ - y_) ** 2).sum(-1) #8, 1000, 1500

inner = (- ((x_ - y_) ** 2).sum(-1) + u_) / eps_

# inner =  Dis2 + u_

out = inner.logsumexp(1)
```
The error is:
```python
Traceback (most recent call last):
  File "debug_script.py", line 52, in <module>
    inner = (- ((x_ - y_) ** 2).sum(-1) + u_) / eps_
  File "/home/lzm/miniconda3/envs/torch14/lib/python3.6/site-packages/pykeops/common/lazy_tensor.py", line 788, in __add__
    return self.binary(other, "+", is_operator=True)
  File "/home/lzm/miniconda3/envs/torch14/lib/python3.6/site-packages/pykeops/common/lazy_tensor.py", line 463, in binary
    res = LazyTensor.join(self, other)  # Merge the attributes and variables of both operands
  File "/home/lzm/miniconda3/envs/torch14/lib/python3.6/site-packages/pykeops/common/lazy_tensor.py", line 367, in join
    ("dtype", "tools", "Genred", "KernelSolve", "ni", "nj", "ranges", "backend"))
  File "/home/lzm/miniconda3/envs/torch14/lib/python3.6/site-packages/pykeops/common/lazy_tensor.py", line 337, in promote
    raise ValueError("Incompatible values for attribute {}: {} and {}.".format(prop, x, y))
ValueError: Incompatible values for attribute ni: 1000 and 8.
```

That seems the broadcast dose not work properly, or do I miss somethings?

PS: I do not use the more friendly generic_logsumexp function simply because it dose not support batch computation. 
It seems I'm in a quite embarassing position, since I would like to use the geoloss library in my algorithm but there seems to be  no easy way to achieve it. Can you give me some advice where I can contribute? (I've used geoloss for some time but quite new to keops.)

**Comment by jeanfeydy** [comment]
Hi @wzm2256 ,

Thanks for your interest in the library!
The behavior you see here is not a bug, but a minor divergence between KeOps and PyTorch syntax. In the formula `inner = (- ((x_ - y_) ** 2).sum(-1) + u_) / eps_`, the `.sum(-1)` formula is implicitly run with `keepdim=True`. Consequently, to perform broadcasting properly, `u_` should be a LazyTensor of shape `(8, 1, 1500, 1)` instead of `(8, 1, 1500)`. In your example, using:

```python
u_ = LazyTensor(u.reshape(8, 1, 1500, 1))
```

should fix your problem. I agree with you that this syntactic divergence is unfortunate: it is a consequence of the current state of the KeOps C++ engine (scalar variables are identified with vectors of size 1), that we've decided to live with for the moment. For more information, you may look at our [first LazyTensor tutorial](http://www.kernel-operations.io/keops/_auto_tutorials/a_LazyTensors/plot_lazytensors_a.html#batch-processing), where we tried to highlight the issue.

With respect to GeomLoss and the lack of batch support: once again, all my apologies for the slow development time... I intended to push KeOps to the best of my abilities (e.g. with #100) before using its routines for optimal performances in GeomLoss. Nevertheless, I understand that upgrading its internal engine from "generic_logsumexps" to LazyTensors to add batch support is becoming a pressing need for most users: I will try to do it as soon as possible, probably for mid-October with a minor release. With a cleaner and more up-to-date implementation of the core algorithms, I should then be able to integrate contributions more quickly.

I hope that this answers you question :-) 

Best regards,
Jean

**Comment by wzm2256** [comment]
@jeanfeydy Hi, thanks for your reply. With your help, I'm able to write a batch version of 'online' routine of geomloss. I created a pull request in geomloss. Hope this can save you some time:)
