### ISSUE TITLE
conda package?

### ISSUE THREAD

**Issue by dvolgyes** [getkeops/keops#107]
As i see many people have issues with installing pykeops,
including me, and the reason is usually compilers, package dependencies, etc.
It would be great to publish (and in case of new versions: maintain) a conda package.

This is really a great package, but the installation is so sensitive that 
similar questions arise over and over again, sometimes with Mac, sometimes with linux,
sometimes with different gcc version, or different python / pytorch versions.

Conda was designed for solving such problems, it would be great to publish a package
on conda-forge or on your own channel. 

https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by dvolgyes** [comment]
And actually i think it would reduce the number of open issues, so it would spare time soon.

**Comment by mihai-spire** [comment]
aye-aye! this has come up before - see [issue 85](https://github.com/getkeops/keops/issues/85)

**Comment by jeanfeydy** [comment]
Hi @dvolgyes ,

Thanks again for your interest in our library!
As in #85, our current understanding is that with KeOps v2.0, maintaining a conda package (on top of pip) has stopped being a pressing issue:

- Compilation times have been reduced from 10+ seconds to a fraction of a second.
- We have removed all the "complex" dependencies (CMake...) of the library. KeOps now only requires a C++ compiler such as gcc/g++, as well as the CUDA toolkit for Nvidia GPUs. This is very similar to e.g. the R or PyTorch dependencies: we think that asking users to install gcc is more sensible than trying to maintain a custom syntax for pre-built binaries.
- We now maintain a Docker image that enables easy deployment on any machine that provides Docker/Singularity, as detailed [here](http://kernel-operations.io/keops/python/installation.html#using-docker-or-singularity).

Notably, we observe an order of magnitude less installation-related issues since the release of the v2.0 engine.
Most remaining issues seem to be related to non-standard PATH for the CUDA toolkit, mostly on shared academic clusters.
These can be set explicitly using the [CUDA_PATH](https://github.com/getkeops/keops/blob/7d68fd9da5887c217937a35210c740b2b9f9f79d/keopscore/keopscore/utils/gpu_utils.py#L78) environment variable.

As a consequence, I would tend to close the issue - but please feel free to re-open if you see a motivation for it.

Best regards,
Jean
