### ISSUE TITLE
Support for block LazyTensors?

### ISSUE THREAD

**Issue by zsteve** [getkeops/keops#146]
Hi Jean,

Wondering if there is currently any support for constructing block matrices from LazyTensors? If not, I wonder if this is something that would be difficult to implement?

e.g. X=[[A, B], [C, D]] where A, B, C, D are each LazyTensors defined by different formulas.

Stephen

**Comment by jeanfeydy** [comment]
Hi @zsteve ,

Thanks (again) for your interest in the library!
I agree with you that this would be an interesting feature to add - and not a difficult one at that. 
We mostly thought about it back in 2019 for applications to physics simulations (where different blocks typically correspond to different types of interactions), but flagged it as low priority and didn't work on it much. There is usually a low-effort work-around in most scenarios, and upgrading our core engine to work with e.g. TensorCores or modern compilation tools seems like a more pressing issue.

In practice, support for block-wide LazyTensors could be implemented fairly easily in the target scripting language (Python, and probably Julia for you!): we can draw inspiration from SciPy's [LinearOperator module](https://github.com/scipy/scipy/blob/v1.6.1/scipy/sparse/linalg/interface.py).

If you believe that the feature is important for you, we can certainly have a talk about it :-)
Best regards,
Jean

**Comment by zsteve** [comment]
Thanks for the detailed response! The motivation from my end is that I'd like to implement the algorithm for quadratically regularised optimal transport (https://arxiv.org/abs/1903.01112, Algorithm 2). But as you mention, should be possible to work something out that can interface with the conjugate gradient solver.

Overall, is there an advantage to using the builtin CG solver in KeOps compared to the SciPy LinearOperator module?

Thanks!
Stephen

**Comment by jeanfeydy** [comment]
Hi @zsteve ,

I see! 
In the short term, the simplest thing to is certainly to feed a custom LinearOperator to SciPy’s conjugate gradient solver, as illustrated in [this tutorial](http://kernel-operations.io/keops/_auto_tutorials/backends/plot_scipy.html).
As detailed in [this benchmark](http://kernel-operations.io/keops/_auto_benchmarks/plot_benchmark_invkernel.html), KeOps’ CG solver is usually a little bit faster than SciPy, but not by much (I will re-do the benchmarks this week-end to check the correctness of the script and the performance gap: I have updated this part of the doc recently and can’t remember if the latest improvements are already online!). This is mostly due to the fact that KeOps can operate fully on the GPU, with float32 numbers if required, whereas the KeOps+SciPy option has to transfer the data between the CPU and the GPU at every iteration. The latter option is thus a little bit wasteful - but realistically, it shouldn’t make much difference for applications to computational biology.

Out of curiosity, may I ask why you are interested in the quadratic regularisation of OT? 
With the recent progresses on entropic OT with annealing, etc. that are discussed in [my PhD thesis](http://jeanfeydy.com/geometric_data_analysis.pdf) and packaged in [GeomLoss](https://www.kernel-operations.io/geomloss/) (that I am going to update next week), we now have access to scalable solvers “for a very small amount of regularisation”, where entropic and quadratic OT both coincide with the genuine Wasserstein distance for all practical purposes. 
With a “higher temperature” and more regularisation, the main “selling point” of entropic OT is that it is smoother and thus more robust to sampling noise... but I haven’t studied quadratic OT much and don’t know what type of setting could motivate its in-depth study. 
I’d be happy to know more and understand your motivations :-)

Best regards,
Jean

**Comment by zsteve** [comment]
Hi @jeanfeydy,

Yes I went ahead and implemented it today, I'm impressed at how seamlessly everything goes together. I'm using the Numpy backend for KeOps and I note that KeOps+Numpy seems to be able to detect and use the GPU for computations involving LazyTensors by default. LazyTensors using the PyTorch backend seem to be incompatible with SciPy (this makes sense to me).

Is it true more generally that KeOps+Numpy stores all data in CPU memory and needs to transfer to GPU for all computations? This is what I suspect, but the last time I looked around the documentation this wasn't entirely clear to me.

The reason I'm interested in solving large-scale OT problems with quadratic regularisation is because the transport plans found using quadratic OT are sparse (see e.g. [here](https://arxiv.org/abs/1710.06276) ), and have the form P_ij ~ relu(u_i + v_j - C_ij). 
Therefore, in applications where we want to use the transport plan itself (rather than the OT loss), this has some benefits to interpretability, etc. 

In some of our recent work [here](https://www.biorxiv.org/content/10.1101/2021.03.02.433630v1) (apologies for the shameless self-plug) we found empirically that the quadratic regularisation seems to be more robust to noise or parameter choices in the setting which we consider, which is trying to estimate a Markov chain on a discrete sample of points. Of course, in this setting entropy regularised OT is the "right" regularisation to use at least in the theoretical setting of continuous densities.

**Comment by zsteve** [comment]
FYI, my implementation of the quadratic regularised OT solution algorithm is [here](https://github.com/zsteve/StationaryOT/blob/main/statot/keops.py), see `quad_ot_semismooth_newton()`.

**Comment by jeanfeydy** [comment]
Hi @zsteve ,

Thanks a lot for your detailed response :-)
To answer your question: indeed, KeOps+NumPy stores all the data on the CPU.
When a reduction of a LazyTensor `K` is called, the inner KeOps engine will either:
- Load the data on the GPU, perform the computation on the device and transfer the results back to the CPU - if a GPU is available.
- Use a parallel for-for loop on the CPU, if no GPU is available or if the user has explicitly set `K.backend = "CPU"`.

In practice, if you don't want to bother with PyTorch, KeOps+NumPy thus provides a very decent level of performance. If `K` is a `(N, M)` LazyTensor, we pay an extra `O(N+M)` price in memory transfers between the CPU and the GPU... But if `N` and `M` are large enough, this should be negligible when compared with the `O(N*M)` cost of the main computation anyway.

If you have any other question, of course, please let us know!
Best regards,
Jean

**Comment by zsteve** [comment]
Thanks again for the info, it certainly makes sense. Agreed, memory location seems to be  second order issue. I do have another (related) question but I will add it in another issue :)
Stephen
