### ISSUE TITLE
Double broadcasting strange behaviour

### ISSUE THREAD

**Issue by btgraham** [getkeops/keops#19]
Hello. I am trying to do `double broadcasting', and I am getting some strange behavior.
Consider 4 point-clouds of 64 points in 3d space.
```
import torch 
from pykeops.torch import LazyTensor
l = torch.randn(4,64,3) #4 point-clouds

#Get the sum of distances-squared between each point cloud: 
l0= l[:,None,:,None,:]
l1= l[None,:,None,:,:]
print(((l0-l1)**2).sum(4).sum(3).sum(2))

#Now try with pykeops
l0=LazyTensor(l0)
l1=LazyTensor(l1)
print(((l0-l1)**2).sum(4).shape) #The reported size is wrong (!), but ...
print(((l0-l1)**2).sum(4).sum(3).sum(2)[:,:,0]) #... output is right, but with an extra singleton dimension.
```
Output
```
tensor([[21983.7969, 23900.2793, 23794.3164, 22217.5625],
        [23900.2773, 24554.8984, 24448.7891, 23295.2148],
        [23794.3164, 24448.7871, 23484.6074, 22879.8828],
        [22217.5625, 23295.2129, 22879.8828, 21782.1055]])
(4, 1, 64, 64)
tensor([[21983.7949, 23900.2793, 23794.3164, 22217.5625],
        [23900.2773, 24554.8984, 24448.7891, 23295.2129],
        [23794.3164, 24448.7871, 23484.6055, 22879.8828],
        [22217.5625, 23295.2129, 22879.8848, 21782.1055]])
```

**Comment by jeanfeydy** [comment]
Hi @btgraham ,

Thanks for your report!
The first problem (the incorrect `(4,1,64,64)` instead of `(4,4,64,64)`) was due to an oversight on my part: it's fixed by https://github.com/getkeops/keops/commit/c5657238c0b3183821aaec18c609b0d95bbd92ad , and will be included in the next PyPi release by mid- or end-September.

Your second point (the extra dummy dimension "1") is more tricky to handle and won't be fixed, unfortunately. As explained in the [LazyTensor tutorial](http://www.kernel-operations.io/keops/_auto_tutorials/a_LazyTensors/plot_lazytensors_a.html#batch-processing), the current behavior is a necessary compromise between two competing uses of `KeOps`: 

1. On one hand, for the sake of mathematical convenience, we want to be able to write formulas such as `((x-y)**2).sum(-1) * v` without throwing shape-related exceptions, and thus default to a `keepdim=True` keyword for the `.sum(-1, ...)` operation. The actual shape of `(l0-l1)**2).sum(4)` is thus equal to `(4,4,64,64,1)`, which allows users to combine it with vector-valued formulas in a transparent way.
2. On the other hand, for duck typing integration with [scipy](http://www.kernel-operations.io/keops/_auto_tutorials/backends/plot_scipy.html#linear-operators), scalar-valued kernel matrices have to present a "collapsed" last dimension: `(l0-l1)**2).sum(4).shape` *must* return `(4,4,64,64)`.

This is the reason why `LazyTensors` have *two* shape attribute:
- `K.shape` for smooth scipy integration,
- and `K._shape`, which is the "genuine" shape of the tensor. 

Anyway, as you noticed already, none of these tuples is used internally by the KeOps engine, which infers the output size directly within the C++ code.

I hope that this answers your question: feel free to re-open the issue  if needed.
Best regards,

Jean

**Comment by btgraham** [comment]
Thank you very much for the explanation.
Can I please check one more thing...
With `l0` and `l1` as above, the return value of 
```((l0-l1)**2).sum(4).sum(3)```
 is already a regular PyTorch Tensor, and it is 64-times larger than the desired final output 
```((l0-l1)**2).sum(4).sum(3).sum(2)```
Is there a way to do the `.sum(2)` operation within PyKeops, rather than in regular PyTorch, please?
