### ISSUE TITLE
ModuleNotFoundError: No module named 'pykeops' on CPU

### ISSUE THREAD

**Issue by gmerca** [getkeops/keops#298]
I am getting this error when running. 
However on python IDE it works.
Is cpu supported ?

`ModuleNotFoundError: No module named 'pykeops'`

I have torch-1.8.1 on cpu-only laptop

**Comment by jeanfeydy** [comment]
Hi @gmerca ,

Thanks for your interest in our library.
To be clear, KeOps fully supports CPU.
I suspect that your issue was due to the fact that you have two Python configurations on your machine - e.g. one native, and one for your IDE ; or several conda environment. It seems likely that you installed KeOps in your IDE (pip install pykeops), but not for the "pip" of your native Python. This [link](https://docs.python.org/3/installing/index.html#basic-usage) may help you to use the "correct" pip.

Best regards,
Jean
