### ISSUE TITLE
minres solver

### ISSUE THREAD

**Issue by dme65** [getkeops/keops#32]
Hi,

Thank you for working on this amazing project! I've had a lot of luck using it for large-scale GP regression. I was wondering if there are any plans for implementing a minres solver? That would be very useful for kernels that are not necessarily positive definite. As an example, I'm interested in using KeOps for radial basis function interpolation with the conditionally positive definite cubic and thin-plate spline kernels. In this setting, you need to solve linear systems with a symmetric, but not positive definite, kernel matrix.

Best,
David

**Comment by jeanfeydy** [comment]
Hi @dme65 ,

Thanks for you feedback!
Indeed, non-positive kernels are of utmost interest to us: @joanglaunes , @bcharlier  and myself all come from (bio-medical) shape analysis, where thin plate splines provide a reference baseline.

Now, you're right: out-of-the-box, the [`.solve()`](http://www.kernel-operations.io/keops/python/api/pytorch/LazyTensor.html#pykeops.torch.LazyTensor.solve) method for KeOps LazyTensors merely implements a conjugate gradient solver, that is only suitable for positive definite kernels. (Advanced) linear algebra is not our forte, and we cannot over-extend towards a full support of the linalg stack on our binders...

However, as discussed in our [tutorials](http://www.kernel-operations.io/keops/_auto_tutorials/backends/plot_scipy.html), KeOps can be neatly interfaced with standard linear algebra libraries, including [Scipy](https://docs.scipy.org/doc/scipy/reference/sparse.linalg.html)! By-and-large, [our best performances](http://www.kernel-operations.io/keops/_auto_benchmarks/plot_benchmark_invkernel.html) for GP regression come with these robust and well-tested routines: [`scipy.sparse.linalg.cg`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.cg.html), etc. The [GPytorch](https://gpytorch.ai/) developers are also working actively on integrating a KeOps backend with their large-scale solvers, and will probably come up with interesting results in the next few weeks.

In your case, you could simply use the [`scipy.sparse.linalg.minres`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.minres.html) solver as follows:

```python
import numpy as np
from pykeops.numpy import LazyTensor
from scipy.sparse.linalg import aslinearoperator, minres
from scipy.sparse.linalg.interface import IdentityOperator
dtype = 'float32'  # Much faster on gaming GPU (GTX/RTX ranges)

# Draw some points and velocities:
N, D = 10000, 2
x = np.random.rand(N, D).astype(dtype)
v = np.random.rand(N, D).astype(dtype)

# Create the kernel matrix:
x_i = LazyTensor(x[:,None,:])  # (N,1,D)
x_j = LazyTensor(x[None,:,:])  # (1,N,D)
D_ij = ((x_i - x_j) ** 2).sum(-1)  # (N,N,D) -> (N,N)
K_ij = .5 * D_ij * (.000001 + D_ij).log()  # (N,N) Thin Plate Spline kernel in 2D

# Wrap the operator as a scipy object:
K = aslinearoperator(K_ij)
# Add some "nugget effect" or "ridge regularization" on the diagonal:
A = K + 1. * IdentityOperator((N,N))
A.dtype = np.dtype(dtype)  # Fix a Scipy bug

# Solve the linear system A*p = v.
# (Unfortunately, advanced solvers do not accept "matrix" right hand sides)
p = np.zeros((N, D)).astype(dtype)  # Output buffer
for d in range(D):
    p[:,d] = minres(A, v[:,d])[0]  # Discard the "info" integer

# Check that everything's fine:
print( np.mean(np.abs(A @ p - v)) )
```

Note that I had to cheat a little bit in the definition of `K_ij` to prevent NaN from appearing with the `0 * log(0)` limit. Thin plate splines are pretty important, so it may be worth adding a special rule to make sure that KeOps understands that `0 * log(0) = 0`: I'll discuss it with Benjamin and Joan.

Hope that helps: feel free to ask any other question you may have, or close the issue otherwise :-)
Best regards,

Jean

**Comment by joanglaunes** [comment]
Hello @dme65 ,

Some updates on this topic. First we just added a "x*log(x)" operation in KeOps (branch master) which avoids to use the epsilon shift in the computation of the log, as Jean was suggesting. Also to get a full Thin Plate Spline example, one needs to include the affine part in the linear system. I think the only way to do it currently is to write a custom class for the full linear operation, on top of the KeOps routine. Also this allows to avoid calling several times minres. Here is the updated script:
```python
import numpy as np
from pykeops.numpy import LazyTensor
from scipy.sparse.linalg import aslinearoperator, minres
from scipy.sparse.linalg.interface import IdentityOperator
dtype = 'float32'  # Much faster on gaming GPUs (GTX/RTX ranges)

# Draw some points and velocities:
N, D = 10000, 2
x = np.random.rand(N, D).astype(dtype)
v = np.random.rand(N, D).astype(dtype)

# Create the kernel matrix:
x_i = LazyTensor(x[:,None,:])  # (N,1,D)
x_j = LazyTensor(x[None,:,:])  # (1,N,D)
D_ij = ((x_i - x_j) ** 2).sum(-1)  # (N,N,D) -> (N,N)
K_ij = .5 * D_ij.xlogx()  # (N,N) Thin Plate Spline kernel in 2D

# Define the affine part of the TPS linear system : x concatenated with ones 
xt = np.concatenate((np.ones((N,1),dtype=dtype),x),axis=1)

# regularization coefficient (will replace K_ij by K_ij + ridge_coef * Id)
ridge_coef = 1.0

# Wrap the linear system to solve in a class with "shape" and "matvec" properties, 
# to be used by "aslinearoperator" SciPy function
class TPS_operator:   
    @property   
    def shape(self):
        return ((N+D+1)*D,(N+D+1)*D)
    def matvec(self, p):
        p = p.astype(dtype).reshape((N+D+1,D))
        p1 = p[:N,:]
        p2 = p[N:,:]
        out = np.zeros((N+D+1)*D,dtype=dtype)
        out[:N*D] = (K_ij @ p1 + ridge_coef * p1 + xt @ p2).flatten()
        out[N*D:] = (xt.T @ p1).flatten()
        return out

# Wrap the operator as a scipy object:
A = aslinearoperator(TPS_operator())

# Solve the linear system A*p = vt, where vt is v concatenated with a (D+1)*D matrix of zeros
vt = np.concatenate((v,np.zeros((D+1,D),dtype=dtype))).flatten()
p = minres(A,vt)[0]

# Check that everything's fine:
print( np.mean(np.abs(A @ p - vt)) )
```
Let us know if this is useful and works for you.
Best,
Joan

**Comment by dme65** [comment]
Hi @jeanfeydy and @joanglaunes,

Thank you both for your answers! I got the cubic/tps kernel + linear tail setup to work with the scipy implementation of minres. I added the linear tail in a very similar way:
```
P = np.hstack((np.ones((N, 1)), X)).astype(dtype)
def mvm(x):
    return np.hstack((K @ x[:N] + 1e-6 * x[:N] + P @ x[N:], P.T @ x[:N]))
```
I'm mostly interested in interpolation so I don't have to add much regularization to the kernel as cubic/tps kernels are well-conditioned.  I've spent a lot of time on RBFs in the past and I'm amazed by the performance of KeOps.

Best,
David
