### ISSUE TITLE
Which version of Python is supported by KeOps?

### ISSUE THREAD

**Issue by awav** [getkeops/keops#337]
Hi,

I'm using Python 3.10 and I have trouble compiling pykeops code as in this issue: https://github.com/getkeops/keops/issues/318. However, switching to 3.8 is going to be an effort and I'm not using conda. So, I'm curious if KeOps is indeed supports only Python <= 3.8.

**Comment by jeanfeydy** [comment]
Hi @awav ,

There should be no problem with any [recent Python version](https://devguide.python.org/versions/) (>=3.8 for sure, I'm not too sure about earlier versions).

For reference, I am currently using KeOps with Python 3.10 via our latest image on [DockerHub](https://hub.docker.com/layers/getkeops/keops-full/2.1-geomloss0.2.5-cuda11.8-pytorch2.0.0-python3.10/images/sha256-9e7e2155c3d6713f748e9f042295fd9aafcf100549f061fd676ae394e9c5a636?context=explore). Issue #318 was related to the path to the CUDA toolkit, and had nothing to do with the Python version. (I assume that this solved @kayween 's problem because working with a fresh install of Python untangled some environment variables.)

Please note that during my PostDoc at Imperial College, I needed to use a [specific path](https://github.com/getkeops/keops/blob/4750cea0499656a8844ec907df8e3fb502dc7574/keopscore/keopscore/utils/gpu_utils.py#L79) to follow the conventions of the local sysadmins. You may be running into a very similar issue.
Does this solve your problem?

Best regards,
Jean
