### ISSUE TITLE
unary('Max')

### ISSUE THREAD

**Issue by mglisse** [getkeops/keops#46]
I was using `((LazyTensor(XX[:,None,:])-LazyTensor(XX[None,:,:]))**2).sum(-1)` for norm L^2 and naively tried `(LazyTensor(XX[:,None,:])-LazyTensor(XX[None,:,:])).abs().max(-1)` for the sup norm, but it doesn't seem to be implemented. Adding a struct Max (similar to Sum) that derives from UnaryOp lets me call `unary('Max',dimres=1)` and seems to work. The only tricky parts are avoiding std::max (or other host functions) and getting the initial value right (I kept 0 which was fine for a sup norm, but in general I guess it should be -infinity or lowest, from numeric_limits, depending on the type), unless we take advantage of F::DIM>0, initialize with outF[0], and start the iteration from k=1.
Is `max` (and `min`) missing because of a lack of time and demand, or is there some reason why it would be a bad idea?

**Comment by joanglaunes** [comment]
Hello @mglisse ,
Thanks for pointing this, it was clearly missing ; I just added Min, Max, ArgMin and ArgMax. I also updated the LazyTensor methods, so using `.max(-1)` will work now.

**Comment by joanglaunes** [comment]
By the way I chose to assume that the dimension is at least 1 and initialize via outF[0] as you were suggesting ; since it should be slightly faster. Otherwise we could have used the numeric limits that are defined in core/utils/Infinity.h

**Comment by mglisse** [comment]
Thanks a lot! Feel free to close this issue any time.
Reading your patch raised 2 questions for me, if you have time
- in ArgMax, it looks like the index is stored in type float (not int). Does that mean there is a limit of about 16 million on the shapes of matrices that keops can handle?
- if the performance of those small pieces of C++ code is relevant, should we add `__restrict__` on the arguments and/or keep the reduction output in a local variable and only write that to *out once at the end? Or are they always inlined in a context that makes this useless?

**Comment by joanglaunes** [comment]
You are completely correct about your first point ; when using float type, you will get wrong results if you have dimensions greater than about 16 millions. This is something we thought about when we implemented the ArgMin and ArgMax reductions, but we had no time to adapt the code. But clearly  until we do it, we should prevent in the code the user from using greater dimensions with ArgMin / ArgMax operations and float32 data type. I will try to do this as soon as possible.

Now about your second point, I am not familiar with the `__restrict__` keyword, so maybe it could help indeed. But as you say these codes are supposed to be completely inlined in the Cuda kernel, so I am not sure it will change anything. 
Also about the local variable, my intuition is that we should keep the number of variables inside the cuda kernel as small as possible, so that it keeps using local registers, but again this is only a guess..
