### ISSUE TITLE
ABI incompatibility: -D_GLIBCXX_USE_CXX11_ABI=0

### ISSUE THREAD

**Issue by cstich** [getkeops/keops#47]
I was getting a weird error message when I tried to use `pykeops`. 
Basically this one: 
> undefined symbol: _ZN2at5ErrorC1ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
 
After doing some sleuthing I figured out my distribution (NixOS) compiles `pytorch` with `gcc7` and thus uses the newer ABI that was introduced with `gcc4.8` I think. Then I fixed the issue locally deleting the line in `CMakeLists.txt` that adds sets `-D_GLIBCXX_USE_CXX11_ABI=0`.

Then I dug into the documentation of `pytorch` but couldn't find any reference to setting `-D_GLIBCXX_USE_CXX11_ABI=0`while compiling and also couldn't really figure out what the recommended version of `gcc` is for `pytorch`. I guess I am currently trying to figure whose responsible for the ABI incompatibility (`nix`, `pytorch` documentation, or `pykeops`), so that I can open an issue at the correct place but are people still compiling `pytorch` with `gcc4.8`?

**Comment by bcharlier** [comment]
Hi @cstich ,

the `-D_GLIBCXX_USE_CXX11_ABI=0` flag was indeed added to `CMakeLists.txt` to fix an ABI compatibility issue as you have understood on your own... 

At that time (in 2018), the problem was that Pytorch used an old compiler to build its wheel package whereas we were using a newer gcc to compile and link our pykeops modules... The problem was fixed with this flag. 

Now that pyTorch has developed, the flag can surely be removed on most of the systems. Unfortunately, I have no way to properly check the ABI an instance of pytorch is using... Thence, writing a generic `CMakeLists.txt` working everywhere is still hard...


b.

**Comment by cstich** [comment]
>  Unfortunately, I have no way to properly check the ABI an instance of pytorch is using... 

I am not sure how useful it is but there is

````
>>> import torch
>>> torch._C._GLIBCXX_USE_CXX11_ABI
True
````
that tells you if the installed version of pytorch uses this particular ABI or not.

**Comment by bcharlier** [comment]
sounds promising  indeed :)
