### ISSUE TITLE
Could we use this to develop a deeplearning infer framework like TVM?

### ISSUE THREAD

**Issue by FDInSky** [getkeops/keops#75]
Could we use this to develop a deeplearning infer framework like TVM?

**Comment by jeanfeydy** [comment]
Hi @FDInSky ,

Could you please discuss more precisely what you have in mind?

As far as I can tell, KeOps already fits well within existing deep learning pipelines. Unlike TVM or XLA, which are general purpose accelerators, we provide advanced support for a *specific* (but important) type of computations: **reductions of symbolic matrices**. I don't think that implementing features that are redundant with TVM would really make sense: what matters is to make sure that our routines can be integrated seamlessly within higher-level frameworks.

**KeOps only does one (type of) job, but it does it well.** In this sense, it is more closely related to other "domain-specific" libraries such as [cuDNN](https://developer.nvidia.com/cudnn), [cuBLAS](https://developer.nvidia.com/cublas) or [Kymatio](https://www.kymat.io/) than to general compiling frameworks. In the future, we will expand the range of operations and schemes that are supported by the KeOps engine. However, we only target computations that are related to symbolic matrices: approximation schemes for kernel matrix-vector products, etc. 
We intend to provide support for methods in numerical analysis that leverage the mathematical structure of the problems : among others, the [Nyström](https://en.wikipedia.org/wiki/Low-rank_matrix_approximations) or [Fast and Free Memory](https://arxiv.org/pdf/1909.05600.pdf) methods. In the long run, we believe this will be more valuable to the community than yet another redundant, general purpose compilation tool.

I hope that this answers your question: feel free to re-open the issue otherwise.
Best regards,
Jean
