### ISSUE TITLE
Block Sparse Reduction and PyTorch>=1.5

### ISSUE THREAD

**Issue by antoinediez** [getkeops/keops#97]
## 🐛 Bug

Hello, 

The optional "range" argument does not seem to work with PyTorch>=1.5. 

On the example page ["Block sparse reduction" ](https://www.kernel-operations.io/keops/_auto_examples/pytorch/plot_grid_cluster_pytorch.html#sphx-glr-auto-examples-pytorch-plot-grid-cluster-pytorch-py) on the KeOps website, the relative error between the full and sparse convolutions is quite significant (84%) whereas for the same example but using NumPy it is only 0.15%. The same order of magnitude can be achieved using PyTorch 1.4.0. 

Below a small example which shows an unexpected behaviour on a toy example. 

## To Reproduce

**Problem:** given N particles in a box of size L, regularly scattered on a grid, find for each particle the number of neighbours within a distance R. 

For N=16, L=4 and R=1.1, the problem can be solved using KeOps as shown below. 

```python
import torch
from pykeops.torch import LazyTensor

print('Using pytorch version='+torch.__version__)

use_cuda = torch.cuda.is_available()
dtype = torch.cuda.FloatTensor if use_cuda else torch.FloatTensor

N = 16 

x = torch.tensor([
    [.5,.5],
    [.5,1.5],
    [.5,2.5],
    [.5,3.5],
    [1.5,.5],
    [1.5,1.5],
    [1.5,2.5],
    [1.5,3.5],
    [2.5,.5],
    [2.5,1.5],
    [2.5,2.5],
    [2.5,3.5],
    [3.5,.5],
    [3.5,1.5],
    [3.5,2.5],
    [3.5,3.5]    
    ]).type(dtype)

y = x

from pykeops.torch.cluster import grid_cluster

eps = 1.  # Size of our square bins

x_labels = grid_cluster(x, eps)  # class labels
y_labels = grid_cluster(y, eps)  # class labels


from pykeops.torch.cluster import cluster_ranges_centroids

# Compute one range and centroid per class:
x_ranges, x_centroids, _  = cluster_ranges_centroids(x, x_labels)
y_ranges, y_centroids, _  = cluster_ranges_centroids(y, y_labels)
# Note: x_centroids = x

from pykeops.torch.cluster import sort_clusters

x, x_labels = sort_clusters(x, x_labels)
y, y_labels = sort_clusters(y, y_labels)
# Note: this operation does not modify x and y which were already sorted

#Interaction Radius 
R = 1.1 

#Compute the distance matrix between the centroids and keep those at distance<sqrt(2)R 
D = ((x_centroids[:,None,:] - y_centroids[None,:,:])**2).sum(2)
keep = D < 2*R

from pykeops.torch.cluster import from_matrix
ranges_ij = from_matrix(x_ranges, y_ranges, keep)

x_i, y_j = LazyTensor(x[:, None, :]), LazyTensor(y[None, :, :])
D_ij = ((x_i - y_j) ** 2).sum(dim=2)  # Symbolic (M,N,1) matrix of squared distances
K = (R**2-D_ij).step()  # Symbolic (M,N,1) kernel matrix

b = torch.ones((N,1)).type(dtype)

a_full = K @ b
print('a_full='+str(a_full.reshape(N)))
K.ranges = ranges_ij
a_sparse = K @ b
print('a_sparse='+str(a_sparse.reshape(N)))
```
The output on a standard Google Colab session is:
```python
Using pytorch version=1.6.0+cu101
a_full=tensor([3., 4., 4., 3., 4., 5., 5., 4., 4., 5., 5., 4., 3., 4., 4., 3.],
       device='cuda:0')
a_sparse=tensor([3., 1., 3., 0., 1., 3., 3., 3., 3., 3., 3., 1., 0., 3., 1., 3.],
       device='cuda:0') 
```
The right answer is given by "a_full" (**no** block sparse reduction) and "a_sparse" (**with** block sparse reduction) should return the same tensor but does not. With PyTorch 1.4, again on Google Colab with 

```python
!pip3 install --upgrade pykeops torch==1.4.0
```
the same code produces the correct output: 

```python
Using pytorch version=1.4.0
a_full=tensor([3., 4., 4., 3., 4., 5., 5., 4., 4., 5., 5., 4., 3., 4., 4., 3.],
       device='cuda:0')
a_sparse=tensor([3., 4., 4., 3., 4., 5., 5., 4., 4., 5., 5., 4., 3., 4., 4., 3.],
       device='cuda:0')
```

Hope it can help and thank you for your work so far!

Best, 
Antoine

**Comment by jeanfeydy** [comment]
Hi @antoinediez ,

Thanks a lot for your detailed report: this is a critical silent bug!
Unfortunately, the problem seems to come from within the C++ code: a quick check shows that the `ranges` argument is identical for both PyTorch versions. I will investigate this as soon as possible.

Best regards,
Jean

**Comment by jeanfeydy** [comment]
Good news: I was wrong!

The problem comes from a breaking change in PyTorch v1.5.0 ([release notes](https://github.com/pytorch/pytorch/releases/tag/v1.5.0)): `torch.int()` does not return **contiguous arrays** by default anymore, which causes a silent bug in [`pykeops.torch.cluster.cluster_ranges(...)`](https://github.com/getkeops/keops/blob/816249793519a9fcbab1e692c1cea3d81af12e47/pykeops/torch/cluster/utils.py#L95). As a quick workaround, please use:

```python
ranges_ij = tuple(r.contiguous() for r in ranges_ij)
```
before typing:
```python
K.ranges = ranges_ij
```

Going forward, **this is a critical issue for e.g. [GeomLoss](https://www.kernel-operations.io/geomloss/)**: I will quickly commit a fix in PyKeOps to make sure that the `ranges` are always turned into contiguous arrays before being fed to the C++ KeOps engine. This is an assumption that I had made without putting safety checks in place: all my apologies for the inconvenience...

Best regards,
And see you soon,
Jean

**Comment by antoinediez** [comment]
Hi Jean, 
Great, thank you for your prompt answer! 
Best, 
Antoine
